#! /usr/bin/env php

<?php

use App\CalculateSalaryDateCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application('Output the pay dates for any given year.');

$app->add(new CalculateSalaryDateCommand);

$app->run();
